CREATE DATABASE IF NOT EXISTS btltk;
USE btltk;
CREATE TABLE IF NOT EXISTS users (
	username VARCHAR(100) PRIMARY KEY,
	password VARCHAR(100) NOT NULL,
	nickname VARCHAR(100) NOT NULL,
	avatar VARCHAR(100) NOT NULL,
	status VARCHAR(100) NOT NULL,
	token VARCHAR(100) NOT NULL
);